FROM node:18-alpine AS build

COPY package*.json ./

RUN npm ci


COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /frontend/dist /usr/share/nginx/html
COPY --from=build nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD [ "nginx", "-g", "daemon off;" ]