"""target

Revision ID: 81bea2d054ea
Revises: b76eaf221876
Create Date: 2025-10-19 16:55:34.133133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81bea2d054ea'
down_revision: Union[str, Sequence[str], None] = 'b76eaf221876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_companies', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target_companies', 'is_active')
    # ### end Alembic commands ###
