"""Index

Revision ID: b76eaf221876
Revises: 64223352c809
Create Date: 2025-10-18 12:07:33.479293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76eaf221876'
down_revision: Union[str, Sequence[str], None] = '64223352c809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_leads_status_new', 'leads', ['status'], unique=False, postgresql_where=sa.text("status = 'NEW'"))
    op.create_index('ix_leads_status_processing', 'leads', ['status'], unique=False, postgresql_where=sa.text("status = 'PROCESSING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leads_status_processing', table_name='leads', postgresql_where=sa.text("status = 'PROCESSING'"))
    op.drop_index('ix_leads_status_new', table_name='leads', postgresql_where=sa.text("status = 'NEW'"))
    # ### end Alembic commands ###
