"""Bot Improved

Revision ID: d38c6dc0be1d
Revises: b10c2a37ddeb
Create Date: 2025-10-22 16:23:23.443313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38c6dc0be1d'
down_revision: Union[str, Sequence[str], None] = 'b10c2a37ddeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'phone')
    op.drop_column('telegram_users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('full_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('telegram_users', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
